<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
        
  <table class="table table-dark">
    <thead>
      <tr>
        <th>ID</th>
        <th>EVENT</th>
        <th>DATE</th>
      
      </tr>
    </thead>
    <tbody>
    <?php
    $event=Event::find("");
    for($i=0;$i<count($event);$i++){
    ?>
      <tr>
        <td><?php echo $i+1; ?></td>  
        <td><?php echo $event[$i]->name ?></td>
        <td><?php echo $event[$i]->detail ?></td>
        <td><a style="color:white;" href="<?php echo $this->url->getBaseUri(); ?>event/setID<?php echo $event[$i]->id;?>" class="btn btn-info" id="edit<?php echo $event[$i]->id;?>" name="edit<?php echo $event[$i]->id;?>" value="<?php echo $event[$i]->id;?>">edit</a></td>
        <td><a href="<?php echo $this->url->getBaseUri(); ?>event/deleteID/<?php echo $act[$i]->actid;?>" class="btn btn-danger">delete</a></td>
      </tr>
      <?php 
      }
      ?>
    </tbody>
  </table>
</div>

<li class="nav-item mx-0 mx-lg-1">
       <a href="add/index" class="btn btn-outline-primary"> Add </a>
      </li>

</body>
</html>