 <div class="row">
    <div class="col-sm">
     
    </div>
    <div class="col-sm">
<form action="" method="post" enctype="multipart/form-data">
	<input type="hidden"  name="profileId"  value="<?php echo $profile->id;?>">
  <div class="form-group">
    <label>Email address</label>
    <input type="email" name="email" class="form-control" id="email"   required value="<?php echo $profile->username?>">
  </div>
  
  <div class="form-group">
    <label>Firstname</label>
    <input type="text" name="firstname" class="form-control" id="firstname"   required value="<?php echo $profile->first_name?>"> 
  </div>
  
   <div class="form-group">
    <label>Picture</label>
    <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
  </div>
  <?php if($profile->picture!=''){?>
   <div class="form-group">  
          <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/'.$profile->picture; ?>">
  </div>
  <?php }?>
  <button type="submit" class="btn btn-info">Submit</button>
  
  <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">ABOUT ME!!</h2>
            <hr class="light my-4">
            <img class="rounded-circle img-fluid mb-5 d-block mx-auto" src="<?php echo $this->url->getBaseUri(); ?>public/img/1.jpg" alt="">
            <p class="text-faded mb-4">590610673</p>
            <p class="text-faded mb-4">SUMITRA  KOMLUE</p>
            
        </div>
      </div>
    </section>
    
    <div class="copyright py-4 text-center text-drak">
      <div class="container">
        <small>Copyright &copy; Your Website 2018</small>
      </div>
    </div>
    

</form>
    </div>
    <div class="col-sm">
    </div>
  </div>